[project]
name = "nlp-in-python-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bs4>=0.0.2",
    "gensim>=4.3.3",
    "requests>=2.32.5",
    "textblob>=0.19.0",
    "wordcloud>=1.9.4",
]
